service: aws-python38-webcrawl-layer
frameworkVersion: '2'
configValidationMode: warn

custom:
  stage: prod
  region: ap-southeast-1
  bucket: win0168.caririesservice.com
  imagever: win0168-v1_0_0

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  ecr:
    images:
      win0168-v1_0_0:
        path: ./

functions:
  server:
    timeout: 60
    memorySize: 2048
    image:
      name: ${self:custom.imagever}
    environment:
      BUCKET: ${self:custom.bucket}
